### ISSUE TITLE
Need update example at readme

### ISSUE THREAD

**Issue by rgb-24bit** [honmaple/emacs-maple-modeline#1]
In this commit https://github.com/honmaple/emacs-maple-modeline/commit/445f16f9550df6e3022e992e1782097b6cf8e644 maple-modeline-init has become maple-modeline-mode

**Comment by honmaple** [comment]
fixed https://github.com/honmaple/emacs-maple-modeline/commit/8bea7f13fe22390de9668d5b10159fdee73e097e
